apiVersion: v1
kind: Service
metadata:
  name: flexcub-ui-svc
  namespace: staging
status:
  loadBalancer: {}
spec:
  ports:
    - name: flexcub-ui-svc
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: flexcub-ui
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster